# Додати клієнта
POST https://servicify-xax3.onrender.com/clients
Content-Type: application/json

{
    "name": "Іван Петров",
    "phone": "+380671234567",
    "email": "ivan@example.com"
}

###

# Отримати список клієнтів
GET https://servicify-xax3.onrender.com/clients

###

# Оновити клієнта (заміни <id> на реальний _id із попередньої відповіді)
PUT https://servicify-xax3.onrender.com/clients/67bb9ee5450caebf6bf694f6
Content-Type: application/json

{
    "name": "Іван Петров (оновлено)",
    "phone": "+380671234567",
    "email": "ivan.updated@example.com"
}

###

# Додати автомобіль (заміни <clientId> на _id клієнта)
POST https://servicify-xax3.onrender.com/cars
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 2021,
    "vin": "JTDBR32E970000222",
    "clientId": "67bba4a5ca2c08bc06ee5a8d"
}

###

# Отримати всі автомобілі
GET https://servicify-xax3.onrender.com/cars

###

# Видалити клієнта (заміни <id> на реальний _id)
DELETE https://servicify-xax3.onrender.com/clients/67bba277ca2c08bc06ee5a7c

###

# Додати авто
POST https://servicify-xax3.onrender.com/cars
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Land Cruiser",
    "year": 2000,
    "vin": "JTDBR32E970300001",
    "clientId": "67bb9ee5450caebf6bf694f6"
}

###

# Оновити авто (заміни <id> на _id із відповіді POST)
PUT https://servicify-xax3.onrender.com/cars/<id>
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "vin": "JTDBR32E970000001",
    "clientId": "67bba30aca2c08bc06ee5a85"
}

###

# Видалити авто (заміни <id>)
DELETE https://servicify-xax3.onrender.com/cars/67bba47aca2c08bc06ee5a8a

###

# Отримати всі авто
GET https://servicify-xax3.onrender.com/cars

###

# Додати історію
POST https://servicify-xax3.onrender.com/services
Content-Type: application/json

{
    "carId": "67bc352cf3ab30e19cd4df78",
    "description": "Заміна фігні",
    "cost": 1500
}

###

# Оновити історію (заміни <serviceId>)
PUT https://servicify-xax3.onrender.com/services/67bc352cf3ab30e19cd4df78
Content-Type: application/json

{
    "carId": "67bc352cf3ab30e19cd4df78",
    "description": "Заміна масла та гальмівних колодок 1",
    "cost": 2000
}

###

# Видалити історію (заміни <serviceId>)
DELETE https://servicify-xax3.onrender.com/services/67bc37f67503fbcef1c53317

###

# Отримати історію
GET https://servicify-xax3.onrender.com/services

###

# Додай тестове СТО
POST https://servicify-xax3.onrender.com/stations
Content-Type: application/json

{
    "name": "СТО Київ",
    "location": "Київ, вул. Авто, 1"
}

###
# Отримати список СТО
GET https://servicify-xax3.onrender.com/stations